### ISSUE TITLE
[New Feature]: Neutral/Better if newer version

### ISSUE THREAD

**Issue by OfficialEsco** [Trenly/winget-pkgs#117]
### Description of the new feature/enhancement

Currently we sometimes see `Add version:` when its actually a `New version:`

### Proposed technical implementation details (optional)

Not sure if we're already sorting the current versions as neutral?

**Comment by Trenly** [comment]
We are comparing against the Latest version. I know it will specifically fail in cases that don’t use a semver since the string comparison would say “50a2b4”is less than “f61ac3”, even though the 50a2b4 may be newer.

There are other examples, but basically it boils down to it being string comparison

**Comment by OfficialEsco** [comment]
Just found one that have this issue
2.8.8 is greater than 2.8.20

**Comment by Trenly** [comment]
Yep; Again, string comparison. I’ll see if theres an easy way to implement semver checking

**Comment by OfficialEsco** [comment]
https://stackoverflow.com/questions/55335846/how-to-compare-version-numbers-in-powershell

[System.Version] resolved both of my issues

**Comment by Trenly** [comment]
> https://stackoverflow.com/questions/55335846/how-to-compare-version-numbers-in-powershell
> 
> [System.Version] resolved both of my issues
> 
> edit: adding -beta to the version obv broke it, so def not perfect with all the weird versions we got..

Yeah, definitely not a perfect solution. I’ll keep looking. Maybe I can try casting to a system.version and if that doesn’t work then fallback to string comparison.
