### ISSUE TITLE
[New Feature]: Force small letters and - between spaces

### ISSUE THREAD

**Issue by OfficialEsco** [Trenly/winget-pkgs#119]
### Description of the new feature/enhancement

The available fields are `Commands`, `Protocols`, `FileExtensions`, `Moniker` and `Tags`

I'm a bit unsure about this, so i'd like a little feedback from @jedieaston, @ItzLevvie and maybe @denelon?

* Commands, these do most likely never contain spaces, does it need small letters?
* Protocols, same as Commands
* FileExtensions we could force small letters for consistent sake
* Moniker should force both small letters and - between spaces
* Tags, we should probably force small letters and - between spaces, but what if the tag is a alternative name?

**Comment by denelon** [comment]
I think I would agree with all of these. It certainly helps with readability, and hopefully would reduce other simple mistakes.

**Comment by jedieaston** [comment]
I also agree with all of these.
