### ISSUE TITLE
[New Feature]: User-Agent

### ISSUE THREAD

**Issue by OfficialEsco** [Trenly/winget-pkgs#142]
### Description of the new feature/enhancement

When you try to download https://dl.genymotion.com/releases/genymotion-3.2.1/genymotion-3.2.1.exe via YamlCreate and WinGetCreate you'll get
`[Error] Invalid URL Response - The URL did not return a successful response from the server`
or
`HTTP response was unsuccessful. Status code: Forbidden`

-----
>A User-Agent like `Microsoft-Delivery-Optimization/10.1` is needed to visit this URL, otherwise it will return a Cloudflare captcha page.
>Both WinGetCreate and YamlCreate should put a User-Agent into the session.
>
>_Originally posted by @SpecterShell in https://github.com/microsoft/winget-pkgs/issues/34770#issuecomment-1010045404_

**Comment by OfficialEsco** [comment]
-----

> Should be done in this way:
> ```PowerShell
> $_WebClient.Headers.Add("User-Agent", "Microsoft-Delivery-Optimization/10.1")
> ```
>
> And do not forget `Test-Url`:
>```PowerShell
>$HTTP_Request.Headers.Add("User-Agent", "Microsoft-Delivery-Optimization/10.1")
>```
>![image](https://user-images.githubusercontent.com/56779163/151178392-5fd55624-1ecd-4532-b542-f88921289ff5.png)
>
>_Originally posted by @SpecterShell in https://github.com/microsoft/winget-pkgs/issues/34770#issuecomment-1022230719_

-----

Hmm, this might resolve multiple issues?

>Looks like they changed how they distribute URLs ;
>
>I found the files on their site, but it looks like it requires the request to have the headers set. As long as the header has the 
referrer, then it works. Probably nothing we can do about it for now though
>```
>wget -Headers @{'Referer'='https://www.irfanview.info/files/iview459_setup.exe'} https://www.irfanview.info/files>/iview459_setup.exe -OutFile D:\Users\Trenly\Downloads\Temp\iview_wget_test.exe
>```
>
>_Originally posted by @Trenly in https://github.com/microsoft/winget-pkgs/issues/38172#issuecomment-1017939727_

----

And for example [TechPowerUp.NVCleanstall](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/TechPowerUp/NVCleanstall)

> Include "/files/" in the URL, remove the hash and use winget's user-agent, i.e.:
> 
> `curl --head --user-agent "winget/xx" https://us2-dl.techpowerup.com/files/NVCleanstall_1.10.0.exe`
> 
> _Originally posted by W1zzardTPU in https://github.com/microsoft/winget-pkgs/issues/32777#issuecomment-953652832_

**Comment by Trenly** [comment]
````raw
PS C:\WINDOWS\system32> Function Test-Url {
>>     Param
>>     (
>>         [Parameter(Mandatory = $true, Position = 0)]
>>         [string] $URL
>>     )
>>     try {
>>         $HTTP_Request = [System.Net.WebRequest]::Create($URL)
>>         $HTTP_Request.Headers.Add("User-Agent", "Microsoft-Delivery-Optimization/10.1")
>>         $HTTP_Response = $HTTP_Request.GetResponse()
>>         $HTTP_Status = [int]$HTTP_Response.StatusCode
>>     } catch {
>>         # Take no action here; If there is an exception, we will treat it like a 404
>>         $HTTP_Status = 404
>>     }
>>     If ($null -eq $HTTP_Response) { $HTTP_Status = 404 }
>>     Else { $HTTP_Response.Close() }
>>
>>     return $HTTP_Status
>> }
>>
PS C:\WINDOWS\system32> Test-Url 'https://dl.genymotion.com/releases/genymotion-3.2.1/genymotion-3.2.1.exe'
404
````
@spectershell - Still get a 404 even when using the user agent.

**Comment by Trenly** [comment]
Figured it out; It's `$HTTP_Request.UserAgent = 'Microsoft-Delivery-Optimization/10.1'`

**Comment by OfficialEsco** [comment]
Looks like this only solved the Genymotion download issue :(

**Comment by vedantmgoyal2009** [comment]
I guess we should add it as a parameter. If default UA doesn't work, then suggest user to enter a UA using a parameter.

**Comment by Trenly** [comment]
> I guess we should add it as a parameter. If default UA doesn't work, then suggest user to enter a UA using a parameter.

No.
If it doesn’t work using a default agent, then it won’t pass the pipelines anyways. 

Also, it isn’t good to have everything as a parameter. If you have more than 5-10 parameters for a single command then there is a good chance that sonething needs to be redesigned.
