### ISSUE TITLE
[Bug]: The behaviour of Sort-Object on CJK characters differs in different environments

### ISSUE THREAD

**Issue by SpecterShell** [Trenly/winget-pkgs#143]
### Brief description of your issue

YamlCreate.ps1 is using `Sort-Object` for sorting tags. However, its result on Chinese characters differs in different locales and even in different versions of PowerShell.

### Steps to reproduce

```PowerShell
@('上传','下载','drive','云','云盘','分享','同步','备份',' 网盘','共享','文件') | Sort-Object
```

### Expected behavior

The result should be the same in different environments.

### Actual behavior

Windows PowerShell in en-US | Windows PowerShell in zh-CN | PowerShell Core in zh-CN
![image](https://user-images.githubusercontent.com/56779163/151174578-237e6405-5169-4f6c-97e7-31ab71b25659.png)

### Environment

```shell
None.
```

**Comment by Trenly** [comment]
As far as I know, this is something thats an issue with powershell itself and not something that I can control. I’m havent been able to find any documentation on how to fix this

**Comment by Trenly** [comment]
I did some more investigating; There is the [PSSessionOption](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.remoting.pssessionoption?view=powershellsdk-1.1.0) class, which I may be able to set the UICulture in? If the UICulture for the session running YamlCreate is always the same, then the sorting might always be the same?

**Comment by Trenly** [comment]
@SpecterShell - does commit https://github.com/trenly/winget-pkgs/commit/fe9c86910ad10ea25b91963e01388e38fd431319 resolve the issue?

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/pull/46912/files
It works. 🎉
However, after the new pull request is published, the script reports
```
SetValueInvocationException: ...\YamlCreate.ps1:2615:1
Line |
2615 |  [Threading.Thread]::CurrentThread.CurrentUICulture = $callingUICultur …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "CurrentUICulture":
     | "Value cannot be null. (Parameter
     | 'value')"

SetValueInvocationException: ...\YamlCreate.ps1:2616:1
Line |
2616 |  [Threading.Thread]::CurrentThread.CurrentCulture = $callingCulture
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "CurrentCulture":
     | "Value cannot be null. (Parameter
     | 'value')"
```
