### ISSUE TITLE
[Bug]: Problem with installer filename

### ISSUE THREAD

**Issue by SpecterShell** [Trenly/winget-pkgs#159]
While downloading https://cloud.06dn.com/api/v3/file/source/114663/XTrans_setup2.5.2B_DeepL-down.exe?sign=PoLS6iB3NxoGzfsdQF-xJrujCMBS7d-kXptzIRDoFBI%3D%3A0, the script got a wrong extension with illegal characters, causing the download fails immediately.
```
❯ [System.IO.Path]::GetExtension('https://cloud.06dn.com/api/v3/file/source/114663/XTrans_setup2.5.2B_DeepL-down.exe?sign=PoLS6iB3NxoGzfsdQF-xJrujCMBS7d-kXptzIRDoFBI%3D%3A0')
.exe?sign=PoLS6iB3NxoGzfsdQF-xJrujCMBS7d-kXptzIRDoFBI%3D%3A0
```

**Comment by Trenly** [comment]
It seems that this would be a bug within .NETs `System.IO.Path` class
I'll see if I can find a workaround
