### ISSUE TITLE
[New Feature]: Decode URLs

### ISSUE THREAD

**Issue by russellbanks** [Trenly/winget-pkgs#178]
### Description of the new feature/enhancement

Lots of urls are encoded and should be decoded in YamlCreate:

Encoded:
`https://github.com/standardnotes/app/releases/download/%40standardnotes%2Fdesktop%403.158.4/standard-notes-3.158.4-win-x64.exe`

Decoded:
`https://github.com/standardnotes/app/releases/download/@standardnotes/desktop@3.158.4/standard-notes-3.158.4-win-x64.exe`

Note `%40` becoming `@` and `%2F` becoming `/`.

### Proposed technical implementation details (optional)

```pwsh
Add-Type -AssemblyName System.Web
$url = "https%3A%2F%2Fwww.example.com%2F"
$decodedUrl = [System.Web.HttpUtility]::UrlDecode($url)
Write-Output $decodedUrl
```

**Comment by SpecterShell** [comment]
Not all URLs can be decoded, for example the following one from `Microsoft.PCManager.CN`:
https://pcmanager.officeplus.cn/mvp/10000/37170/MSPCManagerOffline_20230425.37170.exe?sv=2021-10-04&se=2023-10-23T09%3A37%3A42Z&sr=c&sp=rwdl&sig=NkztR35AG%2Bs2O6WLKr4Dgu9SnlyKiyMqhyupFWkBY2Y%3D
While the original URL is accessible, the decoded one isn't:
https://pcmanager.officeplus.cn/mvp/10000/37170/MSPCManagerOffline_20230425.37170.exe?sv=2021-10-04&se=2023-10-23T09:37:42Z&sr=c&sp=rwdl&sig=NkztR35AG+s2O6WLKr4Dgu9SnlyKiyMqhyupFWkBY2Y=
This is the only case I have encountered so far, so it should be fine.

**Comment by russellbanks** [comment]
> This is the only case I have encountered so far, so it should be fine.

I think the only way to get around this specific case would be to make a head request to the URL after decoding to check that's it still has a 200 status code.
