### ISSUE TITLE
YamlCreate does not create PR when moving package if AutoSubmitPRs is unset

### ISSUE THREAD

**Issue by SpecterShell** [Trenly/winget-pkgs#191]
If AutoSubmitPRs is unset, YamlCreate never asks user to create PRs when moving package.

https://github.com/Trenly/winget-pkgs/blob/ecc3b4c97f50c0c9a78bd7a91f54f7dbc40511e5/Tools/YamlCreate.ps1#L2759-L2765

BTW the value of this setting should be checked case insensitively (i.e. use `-match` instead of `-eq`), e.g., this line uses case-insensitive "always":

https://github.com/Trenly/winget-pkgs/blob/ecc3b4c97f50c0c9a78bd7a91f54f7dbc40511e5/Tools/YamlCreate.ps1#L3199-L3201

while this line uses the case-sensitive "Always":

https://github.com/Trenly/winget-pkgs/blob/ecc3b4c97f50c0c9a78bd7a91f54f7dbc40511e5/Tools/YamlCreate.ps1#L2735-L2737

**Comment by Trenly** [comment]
> BTW the value of this setting should be checked case insensitively (i.e. use -match instead of -eq), e.g., this line uses case-insensitive "always":

`-eq` is case-insensitive, `-ceq` is the case-sensitive version. `-match` shouldn't be used here, since it would return true if someone had the value of `asldfja;dlkfa;ljfdalwaysasdfad`, since it contains the substring `always`

**Comment by SpecterShell** [comment]
> > BTW the value of this setting should be checked case insensitively (i.e. use -match instead of -eq), e.g., this line uses case-insensitive "always":
> 
> `-eq` is case-insensitive, `-ceq` is the case-sensitive version. `-match` shouldn't be used here, since it would return true if someone had the value of `asldfja;dlkfa;ljfdalwaysasdfad`, since it contains the substring `always`

Didn't know `-eq` is case-insensitive. Thanks for your explanation. 🤯

**Comment by Trenly** [comment]
Just to make sure I understand - When moving packages the behavior should be this?

| Setting | Behavior |
| --- | --- |
| Ask | Prompt |
| Never | Do Nothing |
| Always | Submit |
| Unset | Prompt |

Or should the behavior be different for unset/

**Comment by SpecterShell** [comment]
When it is set to "Always", the PR will be created immediately after the branch is pushed to the remote:
https://github.com/Trenly/winget-pkgs/blob/ecc3b4c97f50c0c9a78bd7a91f54f7dbc40511e5/Tools/YamlCreate.ps1#L2735-L2737
https://github.com/Trenly/winget-pkgs/blob/ecc3b4c97f50c0c9a78bd7a91f54f7dbc40511e5/Tools/YamlCreate.ps1#L2749-L2751

When it is set to "Ask", the PR will be created if user chooses "Yes" after all the branches have been pushed to the remote:
https://github.com/Trenly/winget-pkgs/blob/ecc3b4c97f50c0c9a78bd7a91f54f7dbc40511e5/Tools/YamlCreate.ps1#L2759-L2775

And when it is "Never" or unset the script would do nothing - so I end up creating 100+ PRs manually when moving `Apifox.Apifox` to `Ruihu.Apifox`.

**Comment by Trenly** [comment]
Correct - The question is, what should be the "best" behavior for `Unset`
Clearly "Never", "Ask", and "Always" are acting correctly, but would it be better for an unset value to behave like `Ask`, or like `Always`

**Comment by SpecterShell** [comment]
Should be like `Ask`. This is what
https://github.com/Trenly/winget-pkgs/blob/ecc3b4c97f50c0c9a78bd7a91f54f7dbc40511e5/Tools/YamlCreate.ps1#L3199-L3214
does
