### ISSUE TITLE
Improvement in automatic detection of `PackageFamilyName`

### ISSUE THREAD

**Issue by vedantmgoyal2009** [Trenly/winget-pkgs#45]
# Description of the new feature/enhancement

When a user selects manual entering of Installer Hash:
![image](https://user-images.githubusercontent.com/83997633/134314784-d4fa2f10-bd69-4f01-a08c-e18b8bded9b2.png)
then the option for finding `PackageFamilyName` should download the URL instead of throwing an error:
![image](https://user-images.githubusercontent.com/83997633/134314861-2a6c8841-a879-458a-a7f9-a39d6adc629b.png)

# Proposed technical implementation details (optional)
if ($null -eq $script:dest)
&nbsp; download the installer
else
&nbsp; continue with installation of package and find `PackageFamilyName`

**Comment by Trenly** [comment]
@vedantmgoyal2009 can you provide the Package Identifier that you encountered this issue with?

**Comment by vedantmgoyal2009** [comment]
There isn't any package identifier. When there is any MSIX/APPX installer, and we manually enter the hash (the installer does not get downloaded before), we get this error when we select "automatically find PackageFamilyName" because the file does not exist locally.

**Comment by Trenly** [comment]
> There isn't any package identifier. When there is any MSIX/APPX installer, and we manually enter the hash (we do not download the installer), we get this error when we select "automatically find PackageFamilyName" because the file does not exist locally.

Yes, I know that; Is there a package which exists that I can use when testing the fix? In order to test, I need a package which has an APPX or MSIX installer

**Comment by vedantmgoyal2009** [comment]
`PackageIdentifier: Automattic.Simplenote`
https://github.com/Automattic/simplenote-electron/releases/
