### ISSUE TITLE
`Resolves PR Title #48` instead of `Resolves #48`

### ISSUE THREAD

**Issue by OfficialEsco** [Trenly/winget-pkgs#48]
# Description of the new feature/enhancement

I would like to see the full title instead of just the PR Number when adding Resolves in the PR

# Proposed technical implementation details (optional)

Not sure how GitHub does it, but it seems like you need to add `*` or `-` infront of the line like

* Resolves Trenly/winget-pkgs#48

- Resolves Trenly/winget-pkgs#48

Instead of Resolves Trenly/winget-pkgs#48

**Comment by vedantmgoyal2009** [comment]
> Not sure how GitHub does it, but it seems like you need to add `*` or `-` infront of the line like
> 
> * Resolves [`Resolves PR Title #48` instead of `Resolves #48` #48](https://github.com/Trenly/winget-pkgs/issues/48)

Thanks for mentioning this. I searched but could not find anywhere, this trick.

**Comment by OfficialEsco** [comment]
There is this https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
But nothing about displaying the full title

I came across this when we implemented the Resolves and Submit feature because the Resolves line got added to the `-` question array
