### ISSUE TITLE
Problems in parsing the manifest when there is no en-US locale

### ISSUE THREAD

**Issue by vedantmgoyal2009** [Trenly/winget-pkgs#68]
**From logs of workflow run vedantmgoyal2009/winget-pkgs-automation#98 on my repo:**
![image](https://user-images.githubusercontent.com/83997633/135875097-1b015203-4951-4206-870c-311f6c02446f.png)

**Actual behaviour:**
https://github.com/microsoft/winget-pkgs/pull/29305/files

I think the problem occurs because the is only one locale: ko-KR.

**Question:**
Is it compulsory that en-US should be there with a package?

**Comment by vedantmgoyal2009** [comment]
**Existing manifests:** https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/Riiid/pollapo/0.0.14

**Comment by jedieaston** [comment]
That's not the problem, the problem is that `Riiid.pollapo.locale.ko-KR.yaml` has the type `defaultLocale`  when it should have the type `locale`. You can't have two defaults.

**Comment by vedantmgoyal2009** [comment]
I could not understand what are you trying to say. The repo has only one `defaultLocale` i.e. ko-KR

**Comment by jedieaston** [comment]
But your PR has two files in it that both claim they are `ManifestType: defaultLocale`.

**Comment by jedieaston** [comment]
It seems like YamlCreate.ps1 makes assumptions that the defaultLocale will always be en-US (see [1615](https://github.com/Trenly/winget-pkgs/blob/46af6ca2eea13ed9c6d6edefc694fe850a66af5f/Tools/YamlCreate.ps1#L1615) among other places). I wonder if one of those is the problem here.

**Comment by Trenly** [comment]
> It seems like YamlCreate.ps1 makes assumptions that the defaultLocale will always be en-US (see [1615](https://github.com/Trenly/winget-pkgs/blob/46af6ca2eea13ed9c6d6edefc694fe850a66af5f/Tools/YamlCreate.ps1#L1615) among other places). I wonder if one of those is the problem here.

I believe that is the issue; I did look at the version 1.0 script, and it seems the issue may exist there as well, but I haven't tried it.

I'm not sure the best way to fix this. Maybe looking at the last set of manifests, finding the file that has the default locale, and setting it to that?

**Comment by jedieaston** [comment]
> Maybe looking at the last set of manifests, finding the file that has the default locale, and setting it to that?

That's what I usually do.

**Comment by Trenly** [comment]
> This presents a little bit of a problem if the user of YamlCreate.ps1 doesn't know the language listed as default, but I guess they just wouldn't touch any of the fields in defaultLocale?

I think that's a reasonable thing to assume
