### ISSUE TITLE
YamlCreate Settings for Linux

### ISSUE THREAD

**Issue by vedantmgoyal2009** [Trenly/winget-pkgs#71]
# Description of the new feature/enhancement

Some users would like to work with Linux OS. Hence, YamlCreate settings should be supported on Linux too.

**Comment by vedantmgoyal2009** [comment]
@Trenly

**Comment by Trenly** [comment]
> # Description of the new feature/enhancement
> Some users would like to work with Linux OS. Hence, YamlCreate settings should be supported on Linux too.

What needs to be changed for it to work with Linux? If it has anything to do with the filesystem, it may not be practical to do this because of how different the filesystems are

**Comment by jedieaston** [comment]
Have you tried running it with PowerShell on Linux? It should work, given you aren't doing anything with Windows-only libraries (PowerShell knows how to convert the paths).

**Comment by vedantmgoyal2009** [comment]
So after a long search, I found a way... Will be creating PR in a few minutes...
